# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0002_auto_20160213_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='purchase',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
